### ISSUE TITLE
unzipWithProgress is not create inner folders properly after unzipped the zip file

### ISSUE THREAD

**Issue by kumarandena** [triniwiz/nativescript-zip#11]
Hey @triniwiz,

I am trying to unzip the zip file which having inner folders as mentioned in below screenshot, 

Unzipped using WinRAR archiver in windows desktop -
![errr](https://user-images.githubusercontent.com/30895291/35469529-51e8f1ee-035c-11e8-8c84-57d7686c9388.PNG)

Same thing if i tried with zip plugin in nativescript angular application, Its extracted without create inner folder structure as mentioned below,

![screenshot_2018-01-27-10-12-59 1](https://user-images.githubusercontent.com/30895291/35469523-3637fbf2-035c-11e8-9dc2-ac79e5edbce1.png)

How to resolve this!

Thanks!

**Comment by triniwiz** [comment]
Which platform?

**Comment by kumarandena** [comment]
@triniwiz  

Platform - Android

Device - Samsung SM-T231 Tablet

**Comment by aaayushsingh** [comment]
did this get fixed? did you find a solution @kumarandena ?

**Comment by kumarandena** [comment]
@aaayushsingh Don't fixed yet. But if you have control over your server side then try to handle(generate) the Zip files with same Java [library.](http://www.lingala.net/zip4j/) If you try to unzip the same zip file, It should work as expected.

* CompressionHandler - https://www.programcreek.com/java-api-examples/?api=net.lingala.zip4j.core.ZipFile
