### ISSUE TITLE
Zip functionality is not working with NS Cli v4

### ISSUE THREAD

**Issue by kumarandena** [triniwiz/nativescript-zip#14]
Hi @triniwiz,
 
I have tried to zip the folder with NS Cli v4 and Zip plugin v3.0.0 in Nativescript angular application. But got error, 

`JS: unzip error: {"message":"The specified parameter is not a File entity."}`

**Nativescript components info,**
![tns info zip](https://user-images.githubusercontent.com/30895291/39289470-e2506a54-4949-11e8-9a4d-02bb22dab21e.PNG)

**This is how i tried to zip the folder,**
**Component.ts**

 import { Component, OnInit } from "@angular/core";
import { Zip } from "nativescript-zip";
import * as fs from "file-system";
declare var android: any;
@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    public globalpath = android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS).toString();
    public source = fs.Folder.fromPath(
        fs.path.join(this.globalpath + "/" + "Details" + "/" + "SM" + "/" + "601636")
    );
    public dest = fs.Folder.fromPath(
        fs.path.join(this.globalpath + "/" + "Details" + "/" + "SM")
    );
    constructor() { }
    ngOnInit(): void {
    }
    onZip() {
        console.log(" zip processing..")
        console.log("source ", this.source)
        console.log("dest ", this.dest)
        Zip.zip(this.source.path, this.dest.path, null, null)
            .then(() => {
                console.log(`zip succesfully completed`);
            })
            .catch(err => {
                console.log(`unzip error: ${JSON.stringify(err)}`);
            });
    }
} 

Please have a look at this [TinyUrl.zip](https://github.com/triniwiz/nativescript-zip/files/1949954/TinyUrl.zip) sample to reproduce the issue.

Thanks.

**Comment by acharyaks90** [comment]
@manojdcoder
Thanks for the solution 

With your first method itself it should be successful. Looking at the code I believe the zip file is written in current app path as asset itself as a file not a folder. You will have to mention the destination file not just folder as your second parameter.

To verify same read and log all entities in your destination before and after writing zip to see if at all something changed.

and Solution by @kumarandena 

` public androidDownloadsPath = android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS).toString();

 zip() {

        //clear the test folder to create new zip folder
        let foldertodelete = fs.knownFolders.documents().getFolder("test");
        if (foldertodelete) {
            foldertodelete.clear()
                .then(res => {
                    console.log("Folder cleared successfully")
                })
                .catch(err => {
                    console.log("Error" + err.stack)
                });
        }
        else {
            console.log("cannot clear already deleted folder")
        }

        //check the documents folder to cross check zip file after zipped
        fs.knownFolders.documents().getEntities()
            .then(entities => {
                entities.forEach(entity => {
                    console.log("****************** before - avail something******************")
                    console.log(entity.name);
                    console.log(entity.path);
                    console.log(entity.lastModified);
                });

            }).catch(err => {
                console.log(err.stack);
            });

        //create dummy files in stuff folder to zip
        let f = fs.Folder.fromPath(fs.knownFolders.temp().path).getFolder("stuff");
        f.getFile("text122.txt");
        f.getFile("image222.jpg");
        f.getFile("doc332.doc");
        f.getFile("pdf442.pdf");
        let path = fs.path.join(fs.knownFolders.temp().path, "stuff");

        //zip the folder
        let desti = fs.path.join(fs.knownFolders.documents().path, "stuff.zip");
        console.log("desti path ", desti);

        Zip.zipWithProgress(path, desti, onZipProgress, false, false)
            .then(() => {
                console.log(`zip succesfully completed`);

                //check zip file exists after zip
                let ttt = fs.path.join(fs.knownFolders.documents().path, "stuff.zip");
                let exists = fs.File.exists(ttt);
                console.log("Does stuff.zip exists: " + exists);

                //copy the zip file to the downloads folder
                let tttfile = fs.File.fromPath(ttt);

                let desti = fs.path.join(this.androidDownloadsPath, "Aud Details");
                let destifolder = fs.Folder.fromPath(desti).getFile("stuff.zip");

                if (destifolder) {
                    let binaryfile = tttfile.readSync(err => {
                        console.log("Error Readsync " + err.stack)
                    });
                    destifolder.writeSync(binaryfile, err => {
                        console.log("Error " + err)
                    });
                }

                //unzip the zip file
                Zip.unzip(ttt, fs.path.join(fs.knownFolders.documents().path, "test"))
                    .then(() => {
                        console.log("unzipped successfully");

                        //check entities after unzip
                        fs.Folder.fromPath(fs.path.join(fs.knownFolders.documents().path, "test", "stuff")).getEntities()
                            .then(entities => {
                                entities.forEach(entity => {
                                    console.log("after zip - avail something")
                                    console.log(entity.name);
                                    console.log(entity.path);
                                    console.log(entity.lastModified);
                                });
                            })
                            .catch(err => {
                                console.log("Error", JSON.stringify(err))
                            });
                    })
                    .catch(err => {
                        console.log("unzip Error " + JSON.stringify(err))
                    })

            })
            .catch(err => {
                console.log(`zip error: ${JSON.stringify(err)}`);
            });

        function onZipProgress(percent: number) {
            console.log(`unzip progress: ${percent}`);
        }
    }`

Output : Console
JS: desti path  /data/data/org.nativescript.TinyUrl/files/stuff.zip
JS: Folder cleared successfully
JS: ****************** before - avail something******************
JS: app
JS: /data/data/org.nativescript.TinyUrl/files/app
JS: Wed May 09 2018 18:56:48 GMT+0530 (IST)
JS: ****************** before - avail something******************
JS: internal
JS: /data/data/org.nativescript.TinyUrl/files/internal
JS: Wed May 09 2018 18:56:27 GMT+0530 (IST)
JS: ****************** before - avail something******************
JS: metadata
JS: /data/data/org.nativescript.TinyUrl/files/metadata
JS: Wed May 09 2018 18:56:27 GMT+0530 (IST)
JS: ****************** before - avail something******************
JS: assetsThumb
JS: /data/data/org.nativescript.TinyUrl/files/assetsThumb
JS: Wed May 09 2018 19:05:18 GMT+0530 (IST)
JS: ****************** before - avail something******************
JS: test
JS: /data/data/org.nativescript.TinyUrl/files/test
JS: Wed May 09 2018 19:06:01 GMT+0530 (IST)
JS: ****************** before - avail something******************
JS: stuff.zip
JS: /data/data/org.nativescript.TinyUrl/files/stuff.zip
JS: Thu Jan 01 1970 05:30:00 GMT+0530 (IST)
JS: zip succesfully completed
JS: Does stuff.zip exists: true
JS: unzipped successfully
JS: after zip - avail something
JS: text122.txt
JS: /data/data/org.nativescript.TinyUrl/files/test/stuff/text122.txt
JS: Wed May 09 2018 19:06:00 GMT+0530 (IST)
JS: after zip - avail something
JS: image222.jpg
JS: /data/data/org.nativescript.TinyUrl/files/test/stuff/image222.jpg
JS: Wed May 09 2018 19:06:00 GMT+0530 (IST)
JS: after zip - avail something
JS: doc332.doc
JS: /data/data/org.nativescript.TinyUrl/files/test/stuff/doc332.doc
JS: Wed May 09 2018 19:06:00 GMT+0530 (IST)
JS: after zip - avail something
JS: pdf442.pdf
JS: /data/data/org.nativescript.TinyUrl/files/test/stuff/pdf442.pdf
JS: Wed May 09 2018 19:06:00 GMT+0530 (IST)
