### ISSUE TITLE
Zip function is not working if destination will be outside(downloads) folders instead of inapp protected folders

### ISSUE THREAD

**Issue by kumarandena** [triniwiz/nativescript-zip#16]
Hey @triniwiz,

I have tried to zip the folder with NS Cli v4 and Zip plugin v3.0.0 in Nativescript angular application.
Platform - android

I cannot able to zip the folder in downloads folder, as mentioned in plugin docs (https://www.npmjs.com/package/nativescript-zip#zip)  if the folder is in inapp protected folders then its returning promise with unzipped successfully console. but i cannot able to see/copy the generated zip file.

regarding this issue i have created a topic [here](https://discourse.nativescript.org/t/zip-the-folder-file-using-nativescript-zip-plugin/5832/1) in nativescript forum.

.Thanks

**Comment by triniwiz** [comment]
fixed: https://github.com/triniwiz/nativescript-zip/commit/c109fc3c295f9ad2460b5259b652340b7a90ce47
