### ISSUE TITLE
Unzipping on Android is not working fine for a zip with some nested files and folders 

### ISSUE THREAD

**Issue by lmoreira1987** [triniwiz/nativescript-zip#23]
### Version.
- ^3.0.2

### Which platform(s) does your issue occur on?
- Android

### Issue.
If I have a download with some nested files and folders inside it is not unzipping correctly.

* Expected result
Folder.zip
Folder
- Folder 1
-- file1.html
-- file2.html
- Folder 2
-- file3.html
-- file4.html
- Folder 3
-- file5.html
-- file6.html
- file7.html
- file8.html
- file9.html
- file10.html

* Actual result
Folder.zip
Folder
- Folder 1
-- file1.html
-- Folder
--- Folder 1
---- file1.html

### Please, tell us how to recreate the issue in as much detail as possible. 
Download a zip file from anywhere (for instance, using nativescript-downloader plugin) and put it in a known folder (e.g. temp). It is creating only 4 or 5 files and the rest is sometimes duplicating. 

### Is there any code involved? 
 - zipFile.extractFile(header, f.toString());

**Comment by triniwiz** [comment]
fixed : https://github.com/triniwiz/nativescript-zip/commit/c109fc3c295f9ad2460b5259b652340b7a90ce47
