### ISSUE TITLE
Cannot read property 'zip4j' of undefined

### ISSUE THREAD

**Issue by hgc2002** [triniwiz/nativescript-zip#28]
The following code works perfectly in iOS but fails in Android:

            import { Zip } from "nativescript-zip";

            Zip.unzip({
                archive: this.path_set.compressed_fullpath,
                directory: this.path_set.destination_folder,
                onProgress: function(percent) {
                    console.log(`unzip progress: ${percent}`);
                }
            }).then(() => {
                console.log(source, 'File is decompressed.');
            });

The error message is:
_Cannot read property 'zip4j' of undefined_

My version info:
Android 8.0 - API 26
tns: 6.2.2
tns-core-modules@6.3.1
tns-android: 6.2.0
nativescript-zip@4.0.2

**Comment by triniwiz** [comment]
I need more info , idk if you updated a project or created a new but you can try nuking the project

**Comment by hgc2002** [comment]
I don't understand what you say. 
Can you make a zip, example, with winzip or 7z, add it as an asset in a NS project and decompress it with NS-ZIP plugin ?? I know the question is strange...

**Comment by hgc2002** [comment]
Ok, after lot more tests, here are the results:

It works fine, not exactly as expected, but fine.
My first mistake was on the import of Zip. My fault.
But Zip.unzip should return a promise that you can execute. It does, but as soon as you get the promise, it start its execution. It does not wait to be resolved, don't know why. 
But this was easy to fix: simply declare it right at the point I need to use it. Then use the "then" part to actually run more actions in case of success.

So, well done. It works good.  Closing this issue.
Regards,
Herman.
