### ISSUE TITLE
npm update?

### ISSUE THREAD

**Issue by EddyVerbruggen** [triniwiz/nativescript-zip#4]
Hey Osei,

Would you mind pushing an update to npm? I'd love to use the `unzipWithProgress` feature since the other one doesn't return a promise when done (I need to know when unzipping is done..).

Thanks!

**Comment by triniwiz** [comment]
Sure :)

**Comment by triniwiz** [comment]
Done `1.2.1`

**Comment by EddyVerbruggen** [comment]
Lovely, thanks!

**Comment by EddyVerbruggen** [comment]
Just to add: works perfectly! (only tested iOS)
