### ISSUE TITLE
iOS - Zip.unzipWithProgress doesn't work - 1.3.1

### ISSUE THREAD

**Issue by mikraus94** [triniwiz/nativescript-zip#5]
Hello,
I used Zip.unzipWithProgress few days ago and it works. I tried it yesterday and I get this error 'ERROR Error: Uncaught (in promise): zip-worker-ios failed'. 

Package.json
"nativescript-zip": "^1.2.1"  - doesn't work
"nativescript-zip": "1.3.1"  - doesn't work

Can you resolve this issue, please?

Android works flawlessly.

```
Zip.unzipWithProgress(tempPath, writePath, this.onTick, true).then(function (unzipped) {
					console.log('unzipped');
				});
```

Thank you

**Comment by triniwiz** [comment]
Use `"nativescript-zip": "~1.2.0"` until the plugin gets updated

**Comment by mikraus94** [comment]
I get same result, error again. Do you have any idea how to temporarily fix it?

**Comment by triniwiz** [comment]
if u did `Zip.unzipWithProgress(tempPath, writePath, this.onTick, true).then(function (unzipped) {
					console.log('unzipped');
				},function(err){console.dir(err)});`

**Comment by mikraus94** [comment]
I've got only same error `CONSOLE LOG file:///app/services/common/unzipper.js:48:44: zip-worker-ios failed`

**Comment by triniwiz** [comment]
can you take a screenshot of the nativescript-zip directory in node_modules

**Comment by mikraus94** [comment]
![image](https://cloud.githubusercontent.com/assets/23478332/26203078/153e7204-3bda-11e7-8a90-729d74d52d6d.png)

**Comment by mikraus94** [comment]
Do you have any news?

**Comment by triniwiz** [comment]
I did't get time to check on this maybe @ddfreiling has ?

**Comment by ddfreiling** [comment]
Hey there, sorry about that. It's actually a bug which I've fixed on my own side, just had not had time to do a Pull Request.

This line is the problem: https://github.com/triniwiz/nativescript-zip/blob/master/zip.ios.ts#L21
when percentage is 0 this is falsy and the receiver thinks it's an error/failed message, when in fact it's not.

Change it to `msg.data.progress != undefined` instead. I do not have time to PR right now, sorry.
