### ISSUE TITLE
Getting compilation warning on Android build.

### ISSUE THREAD

**Issue by smarza** [triniwiz/nativescript-zip#7]
Hi @ddfreiling  @triniwiz @rbasniak,

I got this warning message while building `tns run android`.
However, the plugin seems to work fine.

**Packages**
`tns --version => 3.0.3`
`"tns-android": { "version": "3.0.1" }`
`"nativescript-zip": "^1.3.2"`

Do you know anything about this warning? Is it some to be concern?

Later today, I am going to build with webpack. After that, I will post here if the warning appears in webpack build too.

Thanks.

`
:transformClassesWithDexForF0F1F2F3F4F5F6F7F8Debug
warning: Ignoring InnerClasses attribute for an anonymous inner class
(net.lingala.zip4j.unzip.Unzip$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is not an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(net.lingala.zip4j.unzip.Unzip$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is not an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(net.lingala.zip4j.util.ArchiveMaintainer$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is not an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(net.lingala.zip4j.util.ArchiveMaintainer$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is not an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(net.lingala.zip4j.zip.ZipEngine$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is not an inner class.
:mergeF0F1F2F3F4F5F6F7F8DebugJniLibFolders
`

**Comment by smarza** [comment]
Same warning with webpack.

**Comment by triniwiz** [comment]
Ignore it for now 😄

**Comment by smarza** [comment]
@triniwiz 

Deal :blush:

I'll leave the issue openned, so we can come back to this discuss later.
Please let me know if I can help with anything.

Thanks.
